<?php

return [
    'car_types' => [
        'SUV' => [
            'Toyota Fortuner',
            'Mitsubishi Montero Sport',
            'Ford Everest',
            'Isuzu mu-X',
            'Honda CR-V',
            'Nissan X-Trail',
            'Chevrolet Trailblazer',
            'Subaru Forester',
            'Hyundai Tucson',
            'Kia Sorento',
            'Mazda CX-5',
            'Volkswagen Tiguan',
            'BMW X3',
            'Mercedes-Benz GLC',
            'Audi Q5',
            'Lexus RX',
            'Jeep Wrangler',
            'Land Rover Discovery Sport',
            'Porsche Cayenne',
            'Volvo XC60',
        ],
        'SEDAN' => [
            'Toyota Vios',
            'Honda City',
            'Mitsubishi Mirage G4',
            'Hyundai Accent',
            'Nissan Almera',
            'Ford Figo',
            'Kia Rio',
            'Chevrolet Sail',
            'Volkswagen Jetta',
            'Mazda3',
            'Subaru Impreza',
            'Toyota Corolla',
            'Honda Civic',
            'Kia Forte',
            'Hyundai Elantra',
            'Nissan Sentra',
            'Ford Focus',
            'Mitsubishi Lancer',
            'Suzuki Ciaz',
            'Audi A3',
        ],
        'MOTOR' => [
            'Honda Click 150i',
            'Yamaha Aerox 155',
            'Suzuki Raider J115 Fi',
            'Kawasaki Rouser 180',
            'KTM Duke 390',
            'Vespa Primavera 150',
            'Benelli TNT 135',
            'SYM Bonus X 110',
            'TVS Apache RTR 180',
            'Bajaj Pulsar NS 160',
            'Honda CBR150R',
            'Kawasaki Ninja 400',
            'Yamaha MT-03',
            'Suzuki V-Strom 650',
            'BMW G 310 GS',
            'Ducati Monster 797',
            'Harley-Davidson Sportster Iron 883',
            'KTM 1290 Super Duke R',
            'Triumph Bonneville T120',
            'Indian Chief Vintage',
            'Moto Guzzi V7 III Stone',
        ],
        '3_WHEELS' => [
            'Elio Motors Elio',
            'Arcimoto FUV (Fun Utility Vehicle)',
            'Polaris Slingshot',
            'Morgan EV3',
            'Sondors Electric Car',
            'Can-Am Ryker',
            'Nobe 100',
            'Electra Meccanica Solo',
            'Aptera Paradigm',
            'Trikke Pon-e 48V',
            'Traditional Tricycle',
        ],
        '4_WHEELS' => [
            'Toyota Wigo',
            'Honda Brio',
            'Suzuki Celerio',
            'Hyundai Eon',
            'Mitsubishi Mirage',
            'Nissan Almera',
            'Kia Picanto',
            'Chevrolet Spark',
            'Ford Figo',
            'Volkswagen Polo',
            'Mazda2',
            'Subaru Impreza',
            'Toyota Corolla Altis',
            'Honda Civic',
            'Hyundai Elantra',
            'Nissan Sylphy',
            'Ford Focus',
            'Mitsubishi Lancer',
            'Suzuki Ciaz',
            'Chevrolet Cruze',
        ],
    ],
];
